set_property SRC_FILE_INFO {cfile:{E:/class/Master of ANU/6213_Digital Systems and Microprocessors/my_6213/lab2/my_adder/my_adder.srcs/constrs_1/new/full_adder_constraints_Basys3.xdc} rfile:../../../my_adder.srcs/constrs_1/new/full_adder_constraints_Basys3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports X]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports Y]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports C_in]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports Z]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports C_out]
